import { Inter } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/lib/toolkit/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "ShadCn Learn",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
